spring:
  profiles:
    # =========不同命名空间， 不同组，同名
    active: dev
  # =========不同组，同名配置==========
#    active: info 
    # ===========同组，不同名配置===============
#    active: dev # 开发环境
#    active: test # 测试