server:
  port: 7001


eureka:
  instance:
#    单机服务注册中心
#    hostname: localhost #eureka服务端的实例名称
#  集群
    hostname: eureka7001.com
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
#      单机
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      集群, 7001挂了，7002还在
#      defaultZone: http://eureka7002.com:7002/eureka/
  server:
  #关闭自我保护机制，保证不可用服务被及时踢除
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 2000